### ISSUE TITLE
Demo not letting add elements

### ISSUE THREAD

**Issue by mariohmol** [mariohmol/ng-bpmn#2]
In this demo: https://stackblitz.com/edit/ng-bpmn

We can see that when drag and drop an element gives and forbidden icon.. i dont know why

@nikku can u help on that?

**Comment by mariohmol** [comment]
fixed!!

**Comment by nikku** [comment]
See [this comment](https://github.com/bpmn-io/bpmn-js/issues/937#issuecomment-457790586) for solution to this problem.
